export const myRecentWorksData = [
  {
    title: "AirBrick Infra",
    subtitle: "Design Library App",
    desc: "AirBrick Infra is a comprehensive design library catering to architects, interior designers, and design enthusiasts. It offers a vast collection of design elements, inspirations, and resources to streamline the design process and enhance creativity.",
    cardImage: "airbrick_infra.jpg",
    link: "https://design.airbrickinfra.com",
  },
  {
    title: "TestaOnline",
    subtitle: "An Online Assessment Software",
    desc: "TestaOnline is a cutting-edge online assessment software designed to streamline the assessment process for educational institutions and businesses. It offers a user-friendly interface, customizable assessments, detailed analytics, and secure test delivery.",
    cardImage: "testaonline.jpg",
    link: "https://app.testaonline.com",
  },
  {
    title: "Navankur",
    subtitle: "An Online Agriculture Firm",
    desc: "Navankur is an innovative online agriculture firm dedicated to revolutionizing the agricultural industry. With a focus on sustainable practices and technology-driven solutions, Navankur aims to empower farmers and enhance agricultural productivity.",
    cardImage: "navankur.jpg",
    link: "https://navankur.org",
  },
  {
    title: "Sand And Peaks",
    subtitle: "Tours Booking App",
    desc: "Sand And Peaks is a leading tours booking app offering curated travel experiences to adventurous souls. From serene beach getaways to thrilling mountain expeditions, Sand And Peaks ensures unforgettable travel experiences tailored to individual preferences.",
    cardImage: "sand_and_peaks.jpg",
    link: "https://sandandpeaks.com",
  },
  {
    title: "Virtual Tours India",
    subtitle: "360 Property Virtual Visualization",
    desc: "Virtual Tours India specializes in immersive 360-degree property virtual visualization services. Whether showcasing real estate properties, hotels, or tourist attractions, Virtual Tours India provides engaging and interactive virtual experiences to captivate audiences.",
    cardImage: "virtual_tours_india.jpg",
    link: "https://virtual-tours-india.in",
  },
  {
    title: "ConsultWiki",
    subtitle: "Tech Guides and Consultancy",
    desc: "ConsultWiki is a trusted platform offering comprehensive tech guides and consultancy services to businesses and individuals. From IT infrastructure optimization to digital transformation strategies, ConsultWiki provides expert insights and solutions to navigate the digital landscape.",
    cardImage: "consultwiki.jpg",
    link: "https://consultwiki.com",
  },
  {
    title: "PrinterDriver",
    subtitle: "Driver and Tools for Printers",
    desc: "PrinterDriver offers a wide range of drivers and tools for printers to optimize printing performance and efficiency. With compatibility across various printer brands and models, PrinterDriver ensures seamless printing experiences for both personal and business needs.",
    cardImage: "printerdriver.jpg",
    link: "https://printerdrivers.com",
  },
  {
    title: "HelpEmailTales",
    subtitle: "Email Marketing Solutions",
    desc: "HelpEmailTales provides comprehensive email marketing solutions tailored to businesses of all sizes. From email campaign management to subscriber engagement strategies, HelpEmailTales empowers businesses to reach their target audience effectively and drive measurable results.",
    cardImage: "helpemailtales.jpg",
    link: "https://helpemailtales.com",
  },
];
